services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/config.default.yaml:/app/config.yaml
    depends_on:
      - ollama

  frontend:
    image: node:18
    working_dir: /app/frontend
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
